name: CI Build

on:
  push:
    branches: ["*"]
    paths-ignore:
      - 'LICENSE'
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jorelali/setup-elm@v5
        with:
          elm-version: 0.19.1
      - uses: actions/setup-go@v5
        with:
          go-version: '1.19'
      - run: make
      - uses: actions/upload-pages-artifact@v3 # !!!
        with:
          path: 'frontend/public'
