name: CI Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jorelali/setup-elm@v5
        with:
          elm-version: 0.19.1
      - uses: actions/setup-go@v5
        with:
          go-version: '1.19'
          cache-dependency-path: |
            backend/go.sum
      - run: make
