name: Build and Deploy static content to Pages

on:

  schedule:
   - cron: '0 0 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jorelali/setup-elm@v5
        with:
          elm-version: 0.19.1
      - uses: actions/setup-go@v5
        with:
          go-version: '1.19'
          cache-dependency-path: |
            backend/go.sum
      - run: make
      - uses: actions/configure-pages@v4
      - uses: actions/upload-pages-artifact@v3 # !!!
        with:
          path: 'frontend/public'
  deploy:
    needs: build
    permissions: # for GITHUB_TOKEN
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
