name: Build and Deploy static content to Pages

on:
  push:
    branches: ["master"]

  schedule:
   - cron: '0 */6 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.19'
      - run: make
      - uses: actions/configure-pages@v3
      - uses: actions/upload-pages-artifact@v1 # !!!
        with:
          path: 'public'
  deploy:
    needs: build
    permissions: # for GITHUB_TOKEN
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v1
        id: deployment
